

# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

input {
    accel_profile = flat
    sensitivity = 0
    force_no_accel = true
}

decoration {                                                          
   active_opacity = 0.95
   inactive_opacity = 0.90                                         
   fullscreen_opacity = 1.0                                          
}

debug {
    disable_scale_checks = true
}

#xwayland {                                                                                        
#    force_zero_scaling = true                                                                     
#}   
