# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
# windowrule = match:class .*, float on
windowrule = match:class .*, no_blur off
layerrule = match:namespace eww-dashboard, blur on
layerrule = match:namespace eww-dashboard, ignore_alpha 0.4
windowrule = match:class ^(firefox|zen)$, workspace 2
windowrule = match:class ^(Spotify)$, workspace 10
windowrule = match:class ^(discord)$, workspace 1
windowrule = match:class ^(steam|GeForceNOW)$, workspace 3
windowrule = match:workspace 6, float on
windowrule = match:class ^(kitty)$, group set
